name: sc_solo_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - anndata=0.11.4
  - array-api-compat=1.11.2
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - colorama=0.4.6
  - contourpy=1.3.2
  - cuda-cccl=12.9.27
  - cuda-cccl_win-64=12.9.27
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.9.19
  - cuda-runtime=11.8.0
  - cuda-version=12.9
  - cycler=0.12.1
  - cython=3.0.12
  - double-conversion=3.3.1
  - exceptiongroup=1.2.2
  - filelock=3.18.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.57.0
  - freetype=2.13.3
  - get-annotations=0.1.2
  - graphite2=1.3.13
  - h2=4.2.0
  - h5py=3.13.0
  - harfbuzz=11.1.0
  - hdf5=1.14.3
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - intel-openmp=2025.1.0
  - jinja2=3.1.6
  - joblib=1.5.0
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.17
  - legacy-api-wrap=1.4.1
  - lerc=4.0.0
  - libaec=1.1.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=20.1.4
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.10.19
  - libcurand-dev=10.3.10.19
  - libcurl=8.13.0
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.23
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libglib=2.84.1
  - libhwloc=2.11.2
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.47
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libuv=1.50.0
  - libwebp=1.5.0
  - libwebp-base=1.5.0
  - libxcb=1.16
  - libxml2=2.13.7
  - libxslt=1.1.39
  - libzlib=1.3.1
  - llvmlite=0.44.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=3.0.2
  - matplotlib=3.10.1
  - matplotlib-base=3.10.1
  - mkl=2023.1.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - natsort=8.4.0
  - networkx=3.4.2
  - numba=0.61.2
  - numpy=2.2.5
  - openjpeg=2.5.3
  - openssl=3.5.0
  - pandas=2.2.3
  - patsy=1.0.1
  - pcre2=10.44
  - pillow=10.4.0
  - pip=25.1.1
  - pixman=0.46.0
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pycparser=2.22
  - pynndescent=0.5.13
  - pyparsing=3.2.3
  - pyside6=6.9.0
  - pysocks=1.7.1
  - python=3.12.10
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.2
  - qhull=2020.2
  - qt6-main=6.9.0
  - requests=2.32.3
  - scanpy=1.10.0
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - session-info=1.0.0
  - six=1.17.0
  - statsmodels=0.14.4
  - stdlib-list=0.11.1
  - tbb=2021.13.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tornado=6.4.2
  - tqdm=4.67.1
  - typing_extensions=4.13.2
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - umap-learn=0.5.7
  - unicodedata2=16.0.0
  - urllib3=2.4.0
  - vc=14.3
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - yaml=0.2.5
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - absl-py==2.2.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - annoy==1.17.3
      - anyio==4.9.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - babel==2.17.0
      - batchglm==0.7.4
      - beautifulsoup4==4.13.4
      - biopython==1.85
      - biothings-client==0.4.1
      - bleach==6.2.0
      - cellphonedb==5.0.1
      - chex==0.1.89
      - cloudpickle==3.1.1
      - comm==0.2.2
      - configargparse==1.7
      - dask==2021.4.0
      - debugpy==1.8.14
      - decorator==5.2.1
      - defusedxml==0.7.1
      - diffxpy==0.7.4
      - docrep==0.3.2
      - dynamictreecut==0.1.1
      - etils==1.12.2
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - fbpca==1.0
      - flax==0.10.4
      - fqdn==1.5.1
      - frozenlist==1.6.0
      - fsspec==2025.3.2
      - geosketch==1.3
      - gprofiler-official==1.0.0
      - grpcio==1.71.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - humanize==4.12.3
      - igraph==0.11.8
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - ipykernel==6.29.5
      - ipython==9.2.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.6
      - isoduration==20.11.0
      - jax==0.4.35
      - jaxlib==0.4.35
      - jedi==0.19.2
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.14
      - kneed==0.8.5
      - ktplotspy==0.3.2
      - lazy-loader==0.4
      - leidenalg==0.10.2
      - lightning==2.5.1.post0
      - lightning-utilities==0.14.3
      - locket==1.0.0
      - markdown==3.8
      - matplotlib-inline==0.1.7
      - mistune==3.1.3
      - mizani==0.13.5
      - ml-collections==1.1.0
      - ml-dtypes==0.5.1
      - msgpack==1.1.0
      - mudata==0.3.1
      - multidict==6.4.3
      - multipledispatch==1.0.0
      - mygene==3.2.2
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.4.1
      - notebook-shim==0.2.4
      - numpy-groupies==0.11.2
      - numpyro==0.18.0
      - opt-einsum==3.4.0
      - optax==0.2.4
      - orbax-checkpoint==0.11.5
      - overrides==7.7.0
      - packaging==24.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - partd==1.4.2
      - plotnine==0.14.5
      - pluggy==1.5.0
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.51
      - propcache==0.3.1
      - psutil==7.0.0
      - pure-eval==0.2.3
      - pycirclize==1.9.1
      - pyreadr==0.5.3
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pytest==8.3.5
      - python-json-logger==3.3.0
      - pytorch-lightning==2.5.1.post0
      - pywin32==310
      - pywinpty==2.0.15
      - pyzmq==26.4.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpy2==3.5.17
      - scikit-image==0.25.2
      - scikit-misc==0.5.1
      - scrublet==0.2.3
      - scvi-tools==1.3.0
      - send2trash==1.8.3
      - setuptools==80.4.0
      - simplejson==3.20.1
      - sniffio==1.3.1
      - solo-sc==1.2
      - soupsieve==2.7
      - sparse==0.16.0
      - stack-data==0.6.3
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorstore==0.1.74
      - terminado==0.18.1
      - texttable==1.7.0
      - tifffile==2025.3.30
      - tinycss2==1.4.0
      - torchmetrics==1.7.1
      - torchvision==0.20.1
      - traitlets==5.14.3
      - treescope==0.1.9
      - types-python-dateutil==2.9.0.20241206
      - tzlocal==5.3.1
      - uri-template==1.3.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - xarray==2025.4.0
      - yarl==1.20.0
      - zipp==3.21.0
